[package]
name = "git-slides"
version = "0.6.0"
edition = "2024"
authors = ["Quentin Richert <noreply@richert.co>"]
description = "Navigate through Git commits like presentation slides."
license = "MIT OR Apache-2.0"
repository = "https://github.com/qrichert/git-slides.git"
readme = "README.md"
keywords = ["git", "presentation", "slides", "slideshow", "training"]
categories = ["command-line-utilities", "development-tools"]
# Editor integration ships in the repo but not in the crate.
exclude = ["/plugins"]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
# Output text through a pager.
lessify = "0.6.0"
